package uk.ac.ncl.v1.njsandford.isomorphism;

/**
 * Created by Natalie on 11/04/2017.
 */
public enum SubgraphMotif {

    MATCH, VARIATION, INSERTION, DELETION, DUPLICATION_IN_QUERY, DUPLICATION_IN_SUBJECT, CON_DUPLICATION_IN_QUERY, CON_DUPLICATION_IN_SUBJECT, INVERSION_IN_QUERY, INVERSION_IN_SUBJECT
}
